# Generated by Django 4.2.2 on 2023-06-14 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(choices=[('T', 'Teen'), ('P', 'Parent'), ('B', 'Both')], default=True, max_length=10)),
                ('transaction_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default=True, max_length=10)),
                ('points', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('event_tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(choices=[('T', 'Teen'), ('P', 'Parent'), ('B', 'Both')], default=True, max_length=10)),
                ('total_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='event_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_balance', models.IntegerField()),
                ('event_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.user')),
            ],
        ),
    ]
